# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: nachacham
google_analytics: nachacham
title: Changu K. Posts

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 블로그 이름 정하는게 세상에서 제일 어렵다  #영어 한국어

description: Stylish Jekyll Theme

author:
  name: changu_k
  email: nachacham@gmail.com
  github: changukang
  twitter: nachacham #facebook 아이디
  # facebook: nachacham
  bio:
  bio_k: 주 관심사는 Semantic Web, Python, 전산이론, 논리입니다. 필자에 관한 더 자세한 정보는 "About" 페이지에서 확인 가능합니다. 글들은 오른쪽 상단의 네비게이션 바에서 확인 가능합니다.
  email_md5: 8188786a9f869982ac34d38f2a49e9b3

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

# set it as url of an image
#sidebar_background_image: http://i.imgur.com/zrtsPrW.png

BASE_PATH:

gems:
  - jekyll-paginate
